#!/usr/bin/env python

import roslib
import rospy
import actionlib

from my_sb.msg import DoDishesAction, DoDishesGoal

if __name__ == '__main__':
    rospy.init_node('do_dishes_client')
    client = actionlib.SimpleActionClient('do_dishes', DoDishesAction)

    act = DoDishesAction()
    goal = DoDishesGoal()

    print("Wait for the action server")
    a = client.wait_for_server(rospy.Duration.from_sec(2.0))
    print(a)
#    print("The action server come online")
    # Fill in the goal here
    client.send_goal(goal)
    a = client.wait_for_result(rospy.Duration.from_sec(5.0))
    print(a)
