#! /usr/bin/env python

import roslib
import rospy
import actionlib

from my_sb.msg import DoDishesAction

class DoDishesServer:
  def __init__(self):
    self.server = actionlib.SimpleActionServer('do_dishes', DoDishesAction, self.execute, False)
    self.server.start()

  def execute(self, goal):
    # Do lots of awesome groundbreaking robot stuff here
    self.server.set_succeeded()

if __name__ == '__main__':
  rospy.init_node('do_dishes_server')
  server = DoDishesServer()
  print("serer come online")
  rospy.spin()
